## *Assignment - 2*

In [16]:
import numpy as np

### Arrays

In [17]:
def arrays(arr):
    brr = np.array(arr, float)
    return brr[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### Shape and Reshape

In [15]:
arr = list(map(int,input().strip().split()))[:9]
brr = np.array(arr)
print(np.reshape(brr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten

In [1]:
r = list(map(int, input().split()))
arr = list()
for i in range(r[0]):
    ar = list(map(int, input().split()))
    arr.append(ar)
    
arr = np.array(arr).reshape(r[0],r[1])
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate

In [2]:
n = list(map(int, input().split()))
a = []
b = []
for i in range(n[0]):
    ar = list(map(int, input().split()))
    a.append(ar)
for i in range(n[1]):
    br = list(map(int, input().split()))
    b.append(br)

a = np.array(a)
b = np.array(b)

print(np.concatenate((a,b), axis = 0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeroes and Ones

In [3]:
n = list(map(int, input().split()))

print(np.zeros(n, dtype = np.int))
print(np.ones(n, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### Eye and Identity

In [4]:
np.set_printoptions(legacy = '1.13')

n = list(map(int, input().split()))

print(np.eye(n[0], n[1], k = 0))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics

In [5]:
n =list(map(int, input().split()))
a = []
b = []
for i in range(n[0]):
    ar = list(map(int, input().split()))
    a.append(ar)
for i in range(n[0]):
    br = list(map(int, input().split()))
    b.append(br)
    
a = np.array(a)
b = np.array(b)

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, ceil and Rint

In [6]:
np.set_printoptions(legacy='1.13')

a = list(map(float  , input().split()))
a = np.array(a)

print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod

In [7]:
n = list(map(int, input().split()))

a = []
for i in range(n[0]):
    ar = list(map(int, input().split()))
    a.append(ar)

b = np.sum(a, axis = 0)
print(np.prod(b))


2 2
1 2
3 4
24


### Min and Max

In [8]:
n = list(map(int, input().split()))

a = []
for i in range(n[0]):
    ar = list(map(int, input().split()))
    a.append(ar)

b = np.min(a, axis = 1)
print(np.max(b))

4 2
2 5
3 7
1 3
4 0
3


### Mean, Var and Std

In [9]:
n = list(map(int, input().split()))

a = []
for i in range(n[0]):
    ar = list(map(int, input().split()))
    a.append(ar)

print(np.mean(a, axis = 1))
print(np.var(a, axis = 0))
print(round(np.std(a, axis = None), 11))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross

In [10]:
n = int(input())
a = []
b = []
for i in range(n):
    ar = list(map(int, input().split()))
    a.append(ar)
for i in range(n):
    br = list(map(int, input().split()))
    b.append(br)

a = np.array(a)
b = np.array(b)

print(np.dot(a, b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### Inner and Outer

In [11]:
a = list(map(int, input().split()))
b = list(map(int, input().split()))

a = np.array(a)
b = np.array(b)

print(np.inner(a, b))
print(np.outer(a, b))

0 1
2 3
3
[[0 0]
 [2 3]]


### Polynomials

In [12]:
a = list(map(float, input().split()))
n = int(input())

a = np.array(a)
print(np.polyval(a, n))


1.1 2 3
0
3.0


### Linear Algerbra

In [13]:
n = int(input())
a = []
for i in range(n):
    ar = list(map(float, input().split()))
    a.append(ar)
a= np.array(a)
print(round(np.linalg.det(a),2))


2
1.1 1.1
1.1 1.1
0.0
